---
development:
  adapter: postgresql
  encoding: unicode
  database: TCM_development
  pool: 5
  username: root
  password: dbroot
test:
  adapter: postgresql
  encoding: unicode
  database: TCM_test
  pool: 5
  username: TCM
  password: 
production:
  adapter: postgresql
  encoding: unicode
  database: TCM_production
  pool: 5
  username: root
  password: dbroot
